#!/bin/bash
privateAddr=unit-get private-address
publicAddr=unit-get public-address
relation-set hostname=privateAddr port=80
curl --header "Content-Type: application/json" --request POST --data '{"service": "http-smaster", "private-address":"'"$privateAddr"'","public-address":"'"$publicAddr"'", "port":80 }' https://test-api-ddlrzsfdsc.now.sh/
