#!/bin/bash
set -e
status-set maintenance "Installing dependencies..."
apt-get install -y curl
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh
open-port 80
juju-log "Docker installed! You are all set!"