#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids
import requests
import json

address = unit_get("public-address")
relation = relations()
ids = relation_ids()
#relationInfo = relations_of_type(idMessageBroker)
header = {"Content-Type": "application/json"}
payload = {"service": "kubernetes-master", "public-address": address, "relations": json.dumps(relation), "idsRelat": json.dumps(ids)}
requests.post("https://test-api-ddlrzsfdsc.now.sh/", headers=header, data=json.dumps(payload))
