#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids
import requests
import json

address = unit_get("public-address")
relation = relations()
idMessageBroker = relation_ids()[0]
header = {"Content-Type": "application/json"}
payload = {"service": "kafka", "public-address": address, "host": relation["messagebroker"][idMessageBroker]["kafka/0"]["private-address"], "port": relation["messagebroker"][idMessageBroker]["kafka/0"]["port"]}
requests.post("https://test-api-ddlrzsfdsc.now.sh/", headers=header, data=json.dumps(payload))
