#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids, remote_unit
import requests
import json

address = unit_get("public-address")
SMaster = unit_get("private-address")
relation = relations()
idDockerRegistry = relation_ids()[0]
remoteUnit = remote_unit()
header = {"Content-Type": "application/json"}
payload = {"service": "docker-registry", "public-address": address,
           "host": relation["docker-registry"][idDockerRegistry][remoteUnit]["private-address"]}
requests.post("http://" + SMaster + "/config/registry",
              headers=header, data=json.dumps(payload))
