#!/bin/bash
set -e
status-set maintenance "Installing dependencies..."
apt-get install -y curl python-pip
pip install requests charmhelpers charm-tools
snap install kubectl --classic
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh
open-port 80
