#!/bin/bash
set -e
sudo -u ubuntu /snap/bin/kubectl config set-context juju --cluster=juju
sudo -u ubuntu /snap/bin/kubectl config use-context juju
status-set active "Run Docker container on port 80"
