#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids, remote_unit
import requests
import json
from subprocess import call


address = unit_get("public-address")
relation = relations()
idMessageBroker = relation_ids()[0]
remoteUnit = remote_unit()
header = {"Content-Type": "application/json"}
payload = {"service": "neo4j", "public-address": address,
           "host": relation["graphdb"][idMessageBroker][remoteUnit]["private-address"], "port": 7474}
requests.post("https://test-api-ddlrzsfdsc.now.sh/",
              headers=header, data=json.dumps(payload))

# Set the env
call("echo 'export NEO_PA=" + address + "' >> ~/.bashrc", shell=True)
call("echo 'export NEO_HOST=" + relation["graphdb"][idMessageBroker]
     [remoteUnit]["private-address"] + "' >> ~/.bashrc", shell=True)
call("echo 'export NEO_PORT=" + "7474" + "' >> ~/.bashrc", shell=True)
