#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids
import requests
import json

address = unit_get("public-address")
relation = relations()
idMessageBroker = relation_ids()[0]
header = {"Content-Type": "application/json"}
payload = {"service": "neo4j", "public-address": address, "host": json.dumps(relation), "port": idMessageBroker}
requests.post("https://test-api-ddlrzsfdsc.now.sh/", headers=header, data=json.dumps(payload))
