#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids, remote_unit, config
import requests
import json

address = unit_get("public-address")
relation = relations()
idMessageBroker = relation_ids()[0]
remoteUnit = remote_unit()
config = config()
header = {"Content-Type": "application/json"}
payload = {"service": "neo4j", "public-address": address, "host": json.dumps(relation), "port": 7474, "test": remoteUnit}
requests.post("https://test-api-ddlrzsfdsc.now.sh/", headers=header, data=json.dumps(payload))
