#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids, remote_unit
import requests
import json
from subprocess import call


address = unit_get("public-address")
relation = relations()
idMessageBroker = relation_ids()[0]
remoteUnit = remote_unit()
header = {"Content-Type": "application/json"}
payload = {"service": "kubernetes-master", "public-address": address,
           "host": relation["kubemaster"][idMessageBroker][remoteUnit]["private-address"], "port": relation["kubemaster"][idMessageBroker][remoteUnit]["port"]}
requests.post("https://test-api-ddlrzsfdsc.now.sh/",
              headers=header, data=json.dumps(payload))

# Set the env
call("echo 'export KUBE_PA=" + address + "' >> ~/.bashrc", shell=True)
call("echo 'export KUBE_HOST=" + relation["kubemaster"][idMessageBroker]
     [remoteUnit]["private-address"] + "' >> ~/.bashrc", shell=True)
call("echo 'export KUBE_PORT=" +
     relation["kubemaster"][idMessageBroker][remoteUnit]["port"] + "' >> ~/.bashrc", shell=True)
