#!/usr/bin/env python

from charmhelpers.core.hookenv import unit_get, relations, relation_ids, remote_unit
import requests
import json

address = unit_get("public-address")
SMaster = unit_get("private-address")
relation = relations()
idMessageBroker = relation_ids()[0]
remoteUnit = remote_unit()
header = {"Content-Type": "application/json"}
payload = {"service": "vault", "public-address": address,
           "host": relation["vaultkv"][idMessageBroker][remoteUnit]["private-address"], "port": "default-port"}
requests.post("http://" + SMaster + "/config/vault",
              headers=header, data=json.dumps(payload))
